[language-server]
[language-server.ruby-lsp]
command = "ruby-lsp"
args = ["--debug"]

[[language]]
name = "ruby"
scope = "source.ruby"
injection-regex = "ruby"
file-types = [
  "rb",
  "rake",
  "rakefile",
  "irb",
  "gemfile",
  "gemspec",
  "Rakefile",
  "Gemfile",
  "rabl",
  "jbuilder",
  "feature",
  "jb",
  "Podfile",
  "podspec",
  "Vagrantfile",
  "Brewfile",
  "rjs",
  "rbi",
  "Guardfile",
  "Capfile",
  "Cheffile",
  "Hobofile",
  "Appraisals",
  "Rantfile",
  "Berksfile",
  "Berksfile.lock",
  "Thorfile",
  "Puppetfile",
  "Fastfile",
  "Appfile",
  "Deliverfile",
  "Matchfile",
  "Scanfile",
  "Snapfile",
  "Gymfile"
]
shebangs = ["ruby"]
comment-token = "#"
language-servers = ["solargraph", "scls", "rust-analyzer"]
indent = { tab-width = 2, unit = "" }

[[grammar]]
name = "ruby"
source = { git = "https://github.com/tree-sitter/tree-sitter-ruby", rev = "206c7077164372c596ffa8eaadb9435c28941364" }


[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20     # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true         # completions will return before snippets by default
feature_words = true          # enable completion by word
feature_snippets = true       # enable snippets
feature_unicode_input = true  # enable "unicode input"


# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[language-server.typescript-language-server.config]
plugins = [{  name = "@vue/typescript-plugin", location = "/home/gadiel.rangel/.local/share/fnm/node-versions/v22.12.0/installation/lib/node_modules/@vue/language-server", languages = ["vue"] }]

[language-server.volar]
command = "vue-language-server"
args = ["--stdio"]

[language-server.volar.config]
vue = { hybridMode = false }
typescript = { tsdk = "/home/gadiel.rangel/.local/share/fnm/node-versions/v22.12.0/installation/lib/node_modules/typescript/lib" }

[[language]]
name = "vue"
scope = "source.vue"
injection-regex = "vue"
file-types = ["vue"]
roots = ["package.json", ".git"]
auto-format = true
language-servers = ["volar"]
formatter = { command = 'prettier', args = ["--parser", "vue"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
